export const sessionCopy = {
  it: {
    loading: 'Prepariamo il tuo percorso…', loadError: 'Non riesco ad aprire questo percorso. Rientra dal sito per riprovare.',
    welcome: 'Facciamolo a voce.', intro: 'Una domanda alla volta. Tu rispondi, io ti accompagno.',
    introDetail: 'Potrai interrompermi, chiedere chiarimenti e correggere le risposte. Alla fine le rivediamo insieme.',
    virtual: 'Assistente virtuale', privacyTitle: 'Come vengono usati i tuoi dati',
    privacy: 'Se scegli la voce, l’audio viene inviato a OpenAI per la trascrizione. Le frasi scritte nella conversazione vengono interpretate tramite OpenAI. Inworld genera la voce dell’assistente. Conserviamo per 7 giorni risposte, conversazione e informazioni tecniche sugli errori, comprese le frasi da ricontrollare. Non salviamo registrazioni audio. Dopo la tua conferma, il sito può recuperare le risposte.',
    consent: 'Ho letto come vengono usati i miei dati e desidero continuare.',
    begin: 'Inizia a parlare', beginText: 'Continua scrivendo', return: 'Torna al sito',
    preparing: 'Prepariamo la voce…', ready: 'Pronto quando vuoi', listening: 'Ti ascolto', hearing: 'Ti sto ascoltando…',
    thinking: 'Un momento…', speaking: 'Sto parlando', paused: 'In pausa', reviewing: 'Rivediamo insieme',
    start: 'Inizia la conversazione', resume: 'Riprendi conversazione', pause: 'Metti in pausa',
    write: 'Scrivi invece', voice: 'Passa alla voce', options: 'Mostra le opzioni', hideOptions: 'Nascondi le opzioni',
    voiceHint: 'Rispondi con parole tue. Puoi interrompermi o chiedermi di spiegare.',
    readyHint: 'Attiva il microfono per iniziare. Puoi sempre rispondere scrivendo.',
    pausedHint: 'Prenditi il tuo tempo. Il microfono è in pausa.',
    saved: 'Risposta salvata', edit: 'Modifica', progress: 'Avanzamento', step: 'Domanda', of: 'di',
    confirmValue: 'Ho capito bene?', yes: 'Sì, corretto', change: 'No, correggo',
    reviewTitle: 'Rivediamo le tue risposte.', reviewHint: 'Puoi correggerle prima di confermare.',
    complete: 'Conferma tutte le risposte', answers: 'Le tue risposte', conversation: 'Conversazione', you: 'Tu',
    textLabel: 'Scrivi una risposta o chiedi un chiarimento', send: 'Invia', savedHint: 'Le risposte vengono salvate durante il percorso.',
    finish: 'Tutto pronto', finished: 'Grazie per questo primo incontro.', finishedHint: 'Le tue risposte sono confermate. Torna al sito per proseguire.', continue: 'Continua su',
    voiceError: 'La voce non è disponibile. Puoi riprovare o continuare scrivendo.',
    micError: 'Non riesco ad accedere al microfono. Controlla il permesso nel browser oppure continua scrivendo.',
    requestError: 'Non sono riuscito a salvare la risposta. Riprova: le risposte precedenti sono al sicuro.',
    validationError: 'Controlla la risposta e riprova.', conflict: 'Le risposte sono cambiate. Controlla la domanda e riprova.',
    expired: 'Questa sessione è scaduta. Rientra dal sito per riprendere il percorso.',
    interrupted: 'La conversazione è in pausa. Puoi riprenderla quando vuoi.',
    checkTranscript: 'La domanda è cambiata mentre parlavi. Controlliamo la frase prima di proseguire.',
    useTranscript: 'Usa questa risposta', repeatVoice: 'Ripeti a voce',
    understood: 'Hai detto', notProvided: 'Non indicato', none: 'Nessuno', save: 'Conferma risposta',
    saveEdit: 'Salva correzione', skip: 'Salta', cancel: 'Annulla', add: 'Aggiungi elemento', remove: 'Rimuovi elemento',
  },
  en: {
    loading: 'Getting your session ready…', loadError: 'This session could not be opened. Return to the site to try again.',
    welcome: 'Let’s talk it through.', intro: 'One question at a time. You answer, I guide you.',
    introDetail: 'You can interrupt me, ask for an explanation and correct your answers. We’ll review them together at the end.',
    virtual: 'Virtual assistant', privacyTitle: 'How your data is used',
    privacy: 'If you choose voice, audio is sent to OpenAI for transcription. Messages typed into the conversation are interpreted by OpenAI. Inworld generates the assistant’s voice. We keep answers, conversation and technical error information, including sentences to review, for 7 days. We do not save audio recordings. After you confirm, the site can retrieve your answers.',
    consent: 'I have read how my data is used and would like to continue.',
    begin: 'Start speaking', beginText: 'Continue by typing', return: 'Return to site',
    preparing: 'Getting voice ready…', ready: 'Ready when you are', listening: 'Listening', hearing: 'I’m listening…',
    thinking: 'One moment…', speaking: 'Speaking', paused: 'Paused', reviewing: 'Let’s review',
    start: 'Start conversation', resume: 'Resume conversation', pause: 'Pause conversation',
    write: 'Type instead', voice: 'Switch to voice', options: 'Show options', hideOptions: 'Hide options',
    voiceHint: 'Answer in your own words. You can interrupt me or ask me to explain.',
    readyHint: 'Enable your microphone to begin. You can always answer by typing.',
    pausedHint: 'Take your time. Your microphone is paused.',
    saved: 'Answer saved', edit: 'Edit', progress: 'Progress', step: 'Question', of: 'of',
    confirmValue: 'Did I get that right?', yes: 'Yes, correct', change: 'No, let me correct it',
    reviewTitle: 'Let’s review your answers.', reviewHint: 'You can make corrections before confirming.',
    complete: 'Confirm all answers', answers: 'Your answers', conversation: 'Conversation', you: 'You',
    textLabel: 'Type an answer or ask for clarification', send: 'Send', savedHint: 'Your answers are saved as you go.',
    finish: 'All ready', finished: 'Thank you for this first conversation.', finishedHint: 'Your answers are confirmed. Return to the site to continue.', continue: 'Continue on',
    voiceError: 'Voice is unavailable. Try again or continue by typing.',
    micError: 'I can’t access your microphone. Check your browser permission or continue by typing.',
    requestError: 'Your answer could not be saved. Try again: your previous answers are safe.',
    validationError: 'Check your answer and try again.', conflict: 'Your answers have changed. Check the question and try again.',
    expired: 'This session has expired. Return to the site to resume.',
    interrupted: 'The conversation is paused. Resume whenever you are ready.',
    checkTranscript: 'The question changed while you were speaking. Let’s check the sentence before continuing.',
    useTranscript: 'Use this answer', repeatVoice: 'Say it again',
    understood: 'You said', notProvided: 'Not provided', none: 'None', save: 'Confirm answer',
    saveEdit: 'Save correction', skip: 'Skip', cancel: 'Cancel', add: 'Add item', remove: 'Remove item',
  },
} as const;
